### ISSUE TITLE
Work profile apps

### ISSUE THREAD

**Issue by howardb173** [anod/AppWatcher#84]
Any chance we can detect work profile apps and add them to the list? I've got many apps in a work profile only and they are not detected here in the normal user profile. I've sort of got a fix by installing App Watcher in the work profile as well, but that means I have to check both apps separately and the one in the work profile only works while the profile is "on" (so no timed updates if the profile is "off"). Thanks for any consideration!

**Comment by SPDurkee** [comment]
Installing app watcher in your work profile is the only way you can accomplish what you're trying to do. This is because the work profile is not allowed to communicate with the personal profile and vice versa. If it did it would defeat the entire purpose of an isolated work profile.

Rest assured that your work data is safe and not accessible by any programs in your personal profile, and feel free to install an app in both your personal profile and in your work profile if you need the same functionality in both profiles.

**Comment by howardb173** [comment]
Thanks for the comment - yeah, that's basically what I'd done anyway as I presumed you couldn't access crossover.
